# Progress tracking hook for CollisionOS
# Automatically updates progress files when changes are made

param(
    [string]$FilePath,
    [string]$Operation,
    [string]$Agent = "unknown"
)

# Handle template variables that weren't processed
if ($FilePath -like "*{{ .tool_input.file_path }}*") {
    $FilePath = ""
}
if ($Operation -like "*{{ .tool_name }}*") {
    $Operation = "unknown"
}
if ($Agent -like "*{{ .agent_name }}*") {
    $Agent = "unknown"
}

$projectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$progressDir = Join-Path $projectRoot ".claude\project_updates"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Ensure progress directory exists
if (!(Test-Path $progressDir)) {
    New-Item -ItemType Directory -Path $progressDir -Force | Out-Null
}

# Determine which progress file to update
$progressFile = $null
$category = ""

if ($FilePath -like "*src/components/*" -or $FilePath -like "*src/pages/*") {
    $progressFile = Join-Path $progressDir "frontend_progress.md"
    $category = "Frontend"
}
elseif ($FilePath -like "*server/*" -or $FilePath -like "*api/*") {
    $progressFile = Join-Path $progressDir "backend_progress.md"
    $category = "Backend"
}
elseif ($FilePath -like "*migrations/*" -or $FilePath -like "*.sql") {
    $progressFile = Join-Path $progressDir "database_progress.md"
    $category = "Database"
}
elseif ($FilePath -like "*test*" -or $FilePath -like "*spec*") {
    $progressFile = Join-Path $progressDir "testing_progress.md"
    $category = "Testing"
}
elseif ($FilePath -like "*.yml" -or $FilePath -like "*.yaml" -or $FilePath -like "*Dockerfile*") {
    $progressFile = Join-Path $progressDir "devops_progress.md"
    $category = "DevOps"
}

if ($progressFile) {
    # Create file if it doesn't exist
    if (!(Test-Path $progressFile)) {
        @"
# $category Progress Log

## Auto-generated progress tracking for CollisionOS

---

"@ | Out-File $progressFile -Encoding UTF8
    }
    
    # Append progress entry
    $entry = @"

## [$timestamp] - $Agent - $Operation

### File Modified
- ``$FilePath``

### Operation Type
- $Operation

### Auto-tracked by Hook
This entry was automatically generated by the progress tracking hook.

---

"@
    
    Add-Content -Path $progressFile -Value $entry -Encoding UTF8
    
    Write-Host "Progress tracked: $category - $Operation on $([System.IO.Path]::GetFileName($FilePath))" -ForegroundColor Green
}

exit 0